#!/usr/bin/env python3

# Copyright Aug 2025, Philip Wright. All rights reserved. 

import sys
import traceback
import sqlite3
import os.path
from pw_utils import mydb_utils

note = """
"""

class Bork:
    debug = False
    
    def __init__(self):
        self.script_dir = mydb_utils.get_python_script_dir()
        pass

    def destroy(self, conn):
        arr = [
        "drop table if exists app_ps_lang",
        "drop table if exists app_ps_work",
        "drop table if exists app_ps_edu",
        "drop table if exists app_ps_rel",
        "drop table if exists app_ps_main",
        ]
        cur = conn.cursor()
        for q in arr:
            cur.execute(q)
        return

    def create(self, conn):
        q_main = """
        create table if not exists app_ps_main (
        id                                      integer PRIMARY KEY,
        slate_person_id                         text,
        slate_appl_nbr                          text,
        emplid                                  text,
        duid_t                                  text,
        academic_career                         text,
        admit_term                              text,
        name_prefix                             text,
        name_last                               text,
        name_first                              text,
        name_first_preferred                    text,
        name_middle                             text,
        name_suffix                             text,
        name_maiden_t                           text,
        birth_date                              text,
        birth_place                             text,
        birth_country                           text,
        birth_state                             text,
        gender                                  text,
        marital_status                          text,
        national_id                             text,
        military_status_t                       text,
        citizenship_status_us                   text,
        citizenship_country_non_us_1            text,
        citizenship_country_non_us_2            text,
        address_country_home                    text,
        address_address1_home                   text,
        address_address2_home                   text,
        address_address3_home                   text,
        address_city_home                       text,
        address_county_home                     text,
        address_address_state_home              text,
        address_address_postal_home             text,
        address_country_mail                    text,
        address_address1_mail                   text,
        address_address2_mail                   text,
        address_address3_mail                   text,
        address_city_mail                       text,
        address_address_state_mail              text,
        address_address_postal_mail             text,
        addr_cou_intl_t                         text,
        addr_a1_intl_t                          text,
        addr_a2_intl_t                          text,
        addr_a3_intl_t                          text,
        addr_city_intl_t                        text,
        addr_state_intl_t                       text,
        addr_postal_intl_t                      text,
        addr_cou_work_t                         text,
        addr_a1_work_t                          text,
        addr_a2_work_t                          text,
        addr_a3_work_t                          text,
        addr_city_work_t                        text,
        addr_state_work_t                       text,
        addr_postal_work_t                      text,
        phone_country_code_home                 text,
        phone_number_home                       text,
        phone_country_code_cell                 text,
        phone_number_cell                       text,
        phone_country_code_work                 text,
        phone_number_work                       text,
        phone_number_extension_work             text,
        phone_number_pref_type                  text,
        email_address_other                     text,
        email_address_work                      text,
        email_address_home                      text,
        url_address_skyp                        text,
        ethnic_hispanic_latino                  text,
        ethnic_grp_codes                        text,
        ethnic_grp_addl_dtl                     text,
        religious_preference                    text,
        du_judicatory_t                         text,
        du_district_t                           text,
        du_cert_candidate_t                     text,
        application_center                      text,
        admit_type                              text,
        financial_aid_interest                  text,
        notification_plan                       text,
        application_date                        text,
        application_method                      text,
        academic_level                          text,
        last_school_attended                    text,
        appl_fee_status                         text,
        appl_fee_amt_t                          text,
        appl_fee_paid                           text,
        waive_amt                               text,
        academic_program                        text,
        academic_program_dual_t                 text,
        joint_program_approved_t                text,
        action_reason_t                         text,
        campus_t                                text,
        academic_plan_1                         text,
        academic_sub_plan_1_1_t                 text,
        academic_sub_plan_1_2_t                 text,
        academic_sub_plan_1_3_t                 text,
        academic_plan_2_t                       text,
        plan_sequence_2_t                       text,
        academic_sub_plan_2_1_t                 text,
        academic_sub_plan_2_2_t                 text,
        academic_sub_plan_2_3_t                 text,
        academic_plan_3_t                       text,
        plan_sequence_3_t                       text,
        academic_sub_plan_3_1_t                 text,
        academic_sub_plan_3_2_t                 text,
        academic_sub_plan_3_3_t                 text,
        recruitment_category_multi              text,
        recruitment_category_01_t               text,
        recruitment_sub_category_01_t           text,
        recruitment_description_01_t            text,
        recruitment_category_02_t               text,
        recruitment_sub_category_02_t           text,
        recruitment_description_02_t            text,
        recruitment_category_03_t               text,
        recruitment_sub_category_03_t           text,
        recruitment_description_03_t            text,
        recruitment_category_04_t               text,
        recruitment_sub_category_04_t           text,
        recruitment_description_04_t            text,
        recruitment_category_05_t               text,
        recruitment_sub_category_05_t           text,
        recruitment_description_05_t            text,
        recruitment_category_06_t               text,
        recruitment_sub_category_06_t           text,
        recruitment_description_06_t            text,
        recruitment_category_07_t               text,
        recruitment_sub_category_07_t           text,
        recruitment_description_07_t            text,
        recruitment_category_08_t               text,
        recruitment_sub_category_08_t           text,
        recruitment_description_08_t            text,
        recruitment_category_09_t               text,
        recruitment_sub_category_09_t           text,
        recruitment_description_09_t            text,
        recruitment_category_10_t               text,
        recruitment_sub_category_10_t           text,
        recruitment_description_10_t            text,
        academic_interest_1                     text,
        academic_interest_2                     text,
        academic_interest_3                     text,
        omit                                    text default '',
        appno                                   text default '',
        loaddate                                text default '',
        ps_update_date                          text default ''
        )
        """
        q_rel = """
        create table if not exists app_ps_rel(
        id integer,
        rltnshp_1_people_relation               text,
        rltnshp_1_name                          text,
        rltnshp_1_highest_educ_level            text,
        rltnshp_1_employer                      text,
        rltnshp_1_marital_status                text,
        rltnshp_1_name_prefix                   text,
        rltnshp_1_phone_day                     text,
        rltnshp_1_phone_eve_t                   text,
        rltnshp_1_email                         text,
        rltnshp_1_sex_t                         text,
        rltnshp_1_comments_t                    text,
        rltnshp_1_birth_country                 text,
        rltnshp_1_du_rel_deceased               text,
        rltnshp_1_title                         text,
        rltnshp_1_inst_affiliation_1_alum       text,
        rltnshp_1_institution_1_t               text,
        rltnshp_1_to_dt_1_t                     text,
        rltnshp_1_inst_affiliation_2_employee   text,
        rltnshp_1_institution_2_t               text,
        rltnshp_1_to_dt_2_t                     text,
        rltnshp_2_people_relation               text,
        rltnshp_2_name                          text,
        rltnshp_2_highest_educ_level            text,
        rltnshp_2_employer                      text,
        rltnshp_2_marital_status                text,
        rltnshp_2_name_prefix                   text,
        rltnshp_2_phone_day                     text,
        rltnshp_2_phone_eve_t                   text,
        rltnshp_2_email                         text,
        rltnshp_2_sex_t                         text,
        rltnshp_2_comments_t                    text,
        rltnshp_2_birth_country                 text,
        rltnshp_2_du_rel_deceased               text,
        rltnshp_2_title                         text,
        rltnshp_2_inst_affiliation_1_alum       text,
        rltnshp_2_institution_1_t               text,
        rltnshp_2_to_dt_1_t                     text,
        rltnshp_2_inst_affiliation_2_employee   text,
        rltnshp_2_institution_2_t               text,
        rltnshp_2_to_dt_2_t                     text,
        rltnshp_3_people_relation               text,
        rltnshp_3_name                          text,
        rltnshp_3_highest_educ_level            text,
        rltnshp_3_employer                      text,
        rltnshp_3_marital_status                text,
        rltnshp_3_name_prefix                   text,
        rltnshp_3_phone_day                     text,
        rltnshp_3_phone_eve_t                   text,
        rltnshp_3_email                         text,
        rltnshp_3_sex_t                         text,
        rltnshp_3_comments_t                    text,
        rltnshp_3_birth_country                 text,
        rltnshp_3_du_rel_deceased               text,
        rltnshp_3_title                         text,
        rltnshp_3_inst_affiliation_1_alum       text,
        rltnshp_3_institution_1_t               text,
        rltnshp_3_to_dt_1_t                     text,
        rltnshp_3_inst_affiliation_2_employee   text,
        rltnshp_3_institution_2_t               text,
        rltnshp_3_to_dt_2_t                     text,
        rltnshp_4_people_relation               text,
        rltnshp_4_name                          text,
        rltnshp_4_highest_educ_level            text,
        rltnshp_4_employer                      text,
        rltnshp_4_marital_status                text,
        rltnshp_4_name_prefix                   text,
        rltnshp_4_phone_day                     text,
        rltnshp_4_phone_eve_t                   text,
        rltnshp_4_email                         text,
        rltnshp_4_sex_t                         text,
        rltnshp_4_comments_t                    text,
        rltnshp_4_birth_country                 text,
        rltnshp_4_du_rel_deceased               text,
        rltnshp_4_title                         text,
        rltnshp_4_inst_affiliation_1_alum       text,
        rltnshp_4_institution_1_t               text,
        rltnshp_4_to_dt_1_t                     text,
        rltnshp_4_inst_affiliation_2_employee   text,
        rltnshp_4_institution_2_t               text,
        rltnshp_4_to_dt_2_t                     text,
        rltnshp_5_people_relation               text,
        rltnshp_5_name                          text,
        rltnshp_5_highest_educ_level            text,
        rltnshp_5_employer                      text,
        rltnshp_5_marital_status                text,
        rltnshp_5_name_prefix                   text,
        rltnshp_5_phone_day                     text,
        rltnshp_5_phone_eve_t                   text,
        rltnshp_5_email                         text,
        rltnshp_5_sex_t                         text,
        rltnshp_5_comments_t                    text,
        rltnshp_5_birth_country                 text,
        rltnshp_5_du_rel_deceased               text,
        rltnshp_5_title                         text,
        rltnshp_5_inst_affiliation_1_alum       text,
        rltnshp_5_institution_1_t               text,
        rltnshp_5_to_dt_1_t                     text,
        rltnshp_5_inst_affiliation_2_employee   text,
        rltnshp_5_institution_2_t               text,
        rltnshp_5_to_dt_2_t                     text,
        rltnshp_6_people_relation               text,
        rltnshp_6_name                          text,
        rltnshp_6_highest_educ_level            text,
        rltnshp_6_employer                      text,
        rltnshp_6_marital_status                text,
        rltnshp_6_name_prefix                   text,
        rltnshp_6_phone_day                     text,
        rltnshp_6_phone_eve_t                   text,
        rltnshp_6_email                         text,
        rltnshp_6_sex_t                         text,
        rltnshp_6_comments_t                    text,
        rltnshp_6_birth_country                 text,
        rltnshp_6_du_rel_deceased               text,
        rltnshp_6_title                         text,
        rltnshp_6_inst_affiliation_1_alum       text,
        rltnshp_6_institution_1_t               text,
        rltnshp_6_to_dt_1_t                     text,
        rltnshp_6_inst_affiliation_2_employee   text,
        rltnshp_6_institution_2_t               text,
        rltnshp_6_to_dt_2_t                     text,
        rltnshp_7_people_relation               text,
        rltnshp_7_name                          text,
        rltnshp_7_highest_educ_level            text,
        rltnshp_7_employer                      text,
        rltnshp_7_marital_status                text,
        rltnshp_7_name_prefix                   text,
        rltnshp_7_phone_day                     text,
        rltnshp_7_phone_eve_t                   text,
        rltnshp_7_email                         text,
        rltnshp_7_sex_t                         text,
        rltnshp_7_comments_t                    text,
        rltnshp_7_birth_country                 text,
        rltnshp_7_du_rel_deceased               text,
        rltnshp_7_title                         text,
        rltnshp_7_inst_affiliation_1_alum       text,
        rltnshp_7_institution_1_t               text,
        rltnshp_7_to_dt_1_t                     text,
        rltnshp_7_inst_affiliation_2_employee   text,
        rltnshp_7_institution_2_t               text,
        rltnshp_7_to_dt_2_t                     text,
        rltnshp_8_people_relation               text,
        rltnshp_8_name                          text,
        rltnshp_8_highest_educ_level            text,
        rltnshp_8_employer                      text,
        rltnshp_8_marital_status                text,
        rltnshp_8_name_prefix                   text,
        rltnshp_8_phone_day                     text,
        rltnshp_8_phone_eve_t                   text,
        rltnshp_8_email                         text,
        rltnshp_8_sex_t                         text,
        rltnshp_8_comments_t                    text,
        rltnshp_8_birth_country                 text,
        rltnshp_8_du_rel_deceased               text,
        rltnshp_8_title                         text,
        rltnshp_8_inst_affiliation_1_alum       text,
        rltnshp_8_institution_1_t               text,
        rltnshp_8_to_dt_1_t                     text,
        rltnshp_8_inst_affiliation_2_employee   text,
        rltnshp_8_institution_2_t               text,
        rltnshp_8_to_dt_2_t                     text,
        primary key (id),
        foreign key(id) references app_ps_main(id) on delete cascade)
        """

        q_edu = """
        create table if not exists app_ps_edu(
        id integer,
        educ_1_ext_org_id                       text,
        educ_1_ext_career                       text,
        educ_1_ls_data_source                   text,
        educ_1_transcript_flag                  text,
        educ_1_transcript_type                  text,
        educ_1_transcript_status                text,
        educ_1_ext_acad_level                   text,
        educ_1_transcript_date                  text,
        educ_1_ext_term_type_t                  text,
        educ_1_term_year_t                      text,
        educ_1_received_dt_t                    text,
        educ_1_from_dt_t                        text,
        educ_1_to_dt_t                          text,
        educ_1_ext_summ_type                    text,
        educ_1_unit_type_t                      text,
        educ_1_unt_atmp_total_t                 text,
        educ_1_unt_comp_total_t                 text,
        educ_1_class_rank_t                     text,
        educ_1_class_size_t                     text,
        educ_1_gpa_type_t                       text,
        educ_1_ext_gpa_t                        text,
        educ_1_convert_gpa_t                    text,
        educ_1_percentile_t                     text,
        educ_1_rank_type_t                      text,
        educ_1_comments_1_1_t                   text,
        educ_1_comments_1_2_t                   text,
        educ_1_degree_t                         text,
        educ_1_descr_t                          text,
        educ_1_degree_dt_t                      text,
        educ_1_degree_status_t                  text,
        educ_1_honors_category_t                text,
        educ_1_ext_subj_area_1_1_t              text,
        educ_1_ext_subj_area_1_2_t              text,
        educ_1_field_of_study_1_1_t             text,
        educ_1_field_of_study_1_2_t             text,
        educ_2_ext_org_id                       text,
        educ_2_ext_career                       text,
        educ_2_ls_data_source                   text,
        educ_2_transcript_flag                  text,
        educ_2_transcript_type                  text,
        educ_2_transcript_status                text,
        educ_2_ext_acad_level                   text,
        educ_2_transcript_date                  text,
        educ_2_ext_term_type_t                  text,
        educ_2_term_year_t                      text,
        educ_2_received_dt_t                    text,
        educ_2_from_dt_t                        text,
        educ_2_to_dt_t                          text,
        educ_2_ext_summ_type                    text,
        educ_2_unit_type_t                      text,
        educ_2_unt_atmp_total_t                 text,
        educ_2_unt_comp_total_t                 text,
        educ_2_class_rank_t                     text,
        educ_2_class_size_t                     text,
        educ_2_gpa_type_t                       text,
        educ_2_ext_gpa_t                        text,
        educ_2_convert_gpa_t                    text,
        educ_2_percentile_t                     text,
        educ_2_rank_type_t                      text,
        educ_2_comments_1_1_t                   text,
        educ_2_comments_1_2_t                   text,
        educ_2_degree_t                         text,
        educ_2_descr_t                          text,
        educ_2_degree_dt_t                      text,
        educ_2_degree_status_t                  text,
        educ_2_honors_category_t                text,
        educ_2_ext_subj_area_1_1_t              text,
        educ_2_ext_subj_area_1_2_t              text,
        educ_2_field_of_study_1_1_t             text,
        educ_2_field_of_study_1_2_t             text,
        educ_3_ext_org_id                       text,
        educ_3_ext_career                       text,
        educ_3_ls_data_source                   text,
        educ_3_transcript_flag                  text,
        educ_3_transcript_type                  text,
        educ_3_transcript_status                text,
        educ_3_ext_acad_level                   text,
        educ_3_transcript_date                  text,
        educ_3_ext_term_type_t                  text,
        educ_3_term_year_t                      text,
        educ_3_received_dt_t                    text,
        educ_3_from_dt_t                        text,
        educ_3_to_dt_t                          text,
        educ_3_ext_summ_type                    text,
        educ_3_unit_type_t                      text,
        educ_3_unt_atmp_total_t                 text,
        educ_3_unt_comp_total_t                 text,
        educ_3_class_rank_t                     text,
        educ_3_class_size_t                     text,
        educ_3_gpa_type_t                       text,
        educ_3_ext_gpa_t                        text,
        educ_3_convert_gpa_t                    text,
        educ_3_percentile_t                     text,
        educ_3_rank_type_t                      text,
        educ_3_comments_1_1_t                   text,
        educ_3_comments_1_2_t                   text,
        educ_3_degree_t                         text,
        educ_3_descr_t                          text,
        educ_3_degree_dt_t                      text,
        educ_3_degree_status_t                  text,
        educ_3_honors_category_t                text,
        educ_3_ext_subj_area_1_1_t              text,
        educ_3_ext_subj_area_1_2_t              text,
        educ_3_field_of_study_1_1_t             text,
        educ_3_field_of_study_1_2_t             text,
        educ_4_ext_org_id                       text,
        educ_4_ext_career                       text,
        educ_4_ls_data_source                   text,
        educ_4_transcript_flag                  text,
        educ_4_transcript_type                  text,
        educ_4_transcript_status                text,
        educ_4_ext_acad_level                   text,
        educ_4_transcript_date                  text,
        educ_4_ext_term_type_t                  text,
        educ_4_term_year_t                      text,
        educ_4_received_dt_t                    text,
        educ_4_from_dt_t                        text,
        educ_4_to_dt_t                          text,
        educ_4_ext_summ_type                    text,
        educ_4_unit_type_t                      text,
        educ_4_unt_atmp_total_t                 text,
        educ_4_unt_comp_total_t                 text,
        educ_4_class_rank_t                     text,
        educ_4_class_size_t                     text,
        educ_4_gpa_type_t                       text,
        educ_4_ext_gpa_t                        text,
        educ_4_convert_gpa_t                    text,
        educ_4_percentile_t                     text,
        educ_4_rank_type_t                      text,
        educ_4_comments_1_1_t                   text,
        educ_4_comments_1_2_t                   text,
        educ_4_degree_t                         text,
        educ_4_descr_t                          text,
        educ_4_degree_dt_t                      text,
        educ_4_degree_status_t                  text,
        educ_4_honors_category_t                text,
        educ_4_ext_subj_area_1_1_t              text,
        educ_4_ext_subj_area_1_2_t              text,
        educ_4_field_of_study_1_1_t             text,
        educ_4_field_of_study_1_2_t             text,
        educ_5_ext_org_id                       text,
        educ_5_ext_career                       text,
        educ_5_ls_data_source                   text,
        educ_5_transcript_flag                  text,
        educ_5_transcript_type                  text,
        educ_5_transcript_status                text,
        educ_5_ext_acad_level                   text,
        educ_5_transcript_date                  text,
        educ_5_ext_term_type_t                  text,
        educ_5_term_year_t                      text,
        educ_5_received_dt_t                    text,
        educ_5_from_dt_t                        text,
        educ_5_to_dt_t                          text,
        educ_5_ext_summ_type                    text,
        educ_5_unit_type_t                      text,
        educ_5_unt_atmp_total_t                 text,
        educ_5_unt_comp_total_t                 text,
        educ_5_class_rank_t                     text,
        educ_5_class_size_t                     text,
        educ_5_gpa_type_t                       text,
        educ_5_ext_gpa_t                        text,
        educ_5_convert_gpa_t                    text,
        educ_5_percentile_t                     text,
        educ_5_rank_type_t                      text,
        educ_5_comments_1_1_t                   text,
        educ_5_comments_1_2_t                   text,
        educ_5_degree_t                         text,
        educ_5_descr_t                          text,
        educ_5_degree_dt_t                      text,
        educ_5_degree_status_t                  text,
        educ_5_honors_category_t                text,
        educ_5_ext_subj_area_1_1_t              text,
        educ_5_ext_subj_area_1_2_t              text,
        educ_5_field_of_study_1_1_t             text,
        educ_5_field_of_study_1_2_t             text,
        educ_6_ext_org_id                       text,
        educ_6_ext_career                       text,
        educ_6_ls_data_source                   text,
        educ_6_transcript_flag                  text,
        educ_6_transcript_type                  text,
        educ_6_transcript_status                text,
        educ_6_ext_acad_level                   text,
        educ_6_transcript_date                  text,
        educ_6_ext_term_type_t                  text,
        educ_6_term_year_t                      text,
        educ_6_received_dt_t                    text,
        educ_6_from_dt_t                        text,
        educ_6_to_dt_t                          text,
        educ_6_ext_summ_type                    text,
        educ_6_unit_type_t                      text,
        educ_6_unt_atmp_total_t                 text,
        educ_6_unt_comp_total_t                 text,
        educ_6_class_rank_t                     text,
        educ_6_class_size_t                     text,
        educ_6_gpa_type_t                       text,
        educ_6_ext_gpa_t                        text,
        educ_6_convert_gpa_t                    text,
        educ_6_percentile_t                     text,
        educ_6_rank_type_t                      text,
        educ_6_comments_1_1_t                   text,
        educ_6_comments_1_2_t                   text,
        educ_6_degree_t                         text,
        educ_6_descr_t                          text,
        educ_6_degree_dt_t                      text,
        educ_6_degree_status_t                  text,
        educ_6_honors_category_t                text,
        educ_6_ext_subj_area_1_1_t              text,
        educ_6_ext_subj_area_1_2_t              text,
        educ_6_field_of_study_1_1_t             text,
        educ_6_field_of_study_1_2_t             text,
        accomplishment_lic_cert_1_t             text,
        primary key (id),
        foreign key(id) references app_ps_main(id) on delete cascade)
        """

        q_work = """
        create table app_ps_work(
        id integer,
        work_1_employment_descr_t               text,
        work_1_city_t                           text,
        work_1_country_t                        text,
        work_1_state_t                          text,
        work_1_phone_                           text,
        work_1_start_dt_t                       text,
        work_1_end_dt_t                         text,
        work_1_title_long_t                     text,
        work_1_ending_rate_t                    text,
        work_1_pay_freq_abbrev_t                text,
        work_1_us_sic_cd_t                      text,
        work_1_descrlong_t                      text,
        work_2_employment_descr_t               text,
        work_2_city_t                           text,
        work_2_country_t                        text,
        work_2_state_t                          text,
        work_2_phone_                           text,
        work_2_start_dt_t                       text,
        work_2_end_dt_t                         text,
        work_2_title_long_t                     text,
        work_2_ending_rate_t                    text,
        work_2_pay_freq_abbrev_t                text,
        work_2_us_sic_cd_t                      text,
        work_2_descrlong_t                      text,
        work_3_employment_descr_t               text,
        work_3_city_t                           text,
        work_3_country_t                        text,
        work_3_state_t                          text,
        work_3_phone_                           text,
        work_3_start_dt_t                       text,
        work_3_end_dt_t                         text,
        work_3_title_long_t                     text,
        work_3_ending_rate_t                    text,
        work_3_pay_freq_abbrev_t                text,
        work_3_us_sic_cd_t                      text,
        work_3_descrlong_t                      text,
        work_4_employment_descr_t               text,
        work_4_city_t                           text,
        work_4_country_t                        text,
        work_4_state_t                          text,
        work_4_phone_                           text,
        work_4_start_dt_t                       text,
        work_4_end_dt_t                         text,
        work_4_title_long_t                     text,
        work_4_ending_rate_t                    text,
        work_4_pay_freq_abbrev_t                text,
        work_4_us_sic_cd_t                      text,
        work_4_descrlong_t                      text,
        work_5_employment_descr_t               text,
        work_5_city_t                           text,
        work_5_country_t                        text,
        work_5_state_t                          text,
        work_5_phone_                           text,
        work_5_start_dt_t                       text,
        work_5_end_dt_t                         text,
        work_5_title_long_t                     text,
        work_5_ending_rate_t                    text,
        work_5_pay_freq_abbrev_t                text,
        work_5_us_sic_cd_t                      text,
        work_5_descrlong_t                      text,
        work_6_employment_descr_t               text,
        work_6_city_t                           text,
        work_6_country_t                        text,
        work_6_state_t                          text,
        work_6_phone_                           text,
        work_6_start_dt_t                       text,
        work_6_end_dt_t                         text,
        work_6_title_long_t                     text,
        work_6_ending_rate_t                    text,
        work_6_pay_freq_abbrev_t                text,
        work_6_us_sic_cd_t                      text,
        work_6_descrlong_t                      text,
        work_7_employment_descr_t               text,
        work_7_city_t                           text,
        work_7_country_t                        text,
        work_7_state_t                          text,
        work_7_phone_                           text,
        work_7_start_dt_t                       text,
        work_7_end_dt_t                         text,
        work_7_title_long_t                     text,
        work_7_ending_rate_t                    text,
        work_7_pay_freq_abbrev_t                text,
        work_7_us_sic_cd_t                      text,
        work_7_descrlong_t                      text,
        work_8_employment_descr_t               text,
        work_8_city_t                           text,
        work_8_country_t                        text,
        work_8_state_t                          text,
        work_8_phone_                           text,
        work_8_start_dt_t                       text,
        work_8_end_dt_t                         text,
        work_8_title_long_t                     text,
        work_8_ending_rate_t                    text,
        work_8_pay_freq_abbrev_t                text,
        work_8_us_sic_cd_t                      text,
        work_8_descrlong_t                      text,
        work_9_employment_descr_t               text,
        work_9_city_t                           text,
        work_9_country_t                        text,
        work_9_state_t                          text,
        work_9_phone_                           text,
        work_9_start_dt_t                       text,
        work_9_end_dt_t                         text,
        work_9_title_long_t                     text,
        work_9_ending_rate_t                    text,
        work_9_pay_freq_abbrev_t                text,
        work_9_us_sic_cd_t                      text,
        work_9_descrlong_t                      text,
        work_time_unit_1_t                      text,
        work_time_unit_2_t                      text,
        vendor_id                               text,
        primary key (id),
        foreign key(id) references app_ps_main(id) on delete cascade)
        """

        q_lang = """
        create table app_ps_lang(
        id integer,
        visa_permit_type_t                      text,
        visa_wrkpmt_status_t                    text,
        lang_1_lang_cd                          text,
        lang_1_native_lang                      text,
        lang_1_speak_prof                       text,
        lang_1_read_prof                        text,
        lang_1_write_prof                       text,
        lang_2_lang_cd                          text,
        lang_2_native_lang                      text,
        lang_2_speak_prof                       text,
        lang_2_read_prof                        text,
        lang_2_write_prof                       text,
        lang_3_lang_cd                          text,
        lang_3_native_lang                      text,
        lang_3_speak_prof                       text,
        lang_3_read_prof                        text,
        lang_3_write_prof                       text,
        lang_4_lang_cd                          text,
        lang_4_native_lang                      text,
        lang_4_speak_prof                       text,
        lang_4_read_prof                        text,
        lang_4_write_prof                       text,
        lang_5_lang_cd                          text,
        lang_5_native_lang                      text,
        lang_5_speak_prof                       text,
        lang_5_read_prof                        text,
        lang_5_write_prof                       text,
        primary key(id),
        foreign key(id) references app_ps_main(id) on delete cascade)
        """

        cur = conn.cursor()
        for i,q in enumerate([q_main, q_rel, q_edu, q_work, q_lang]):
            print(i)
            cur.execute(q)
        
        return
        
    def go(self, conn):
        if len(sys.argv[1:]) != 0:
            print("use apool_last_table_create.py")
            sys.exit(-1)
            
        self.destroy(conn)
        self.create(conn)

    pass # class Bork
        
def main():
    conn = None
    try:
        apps_db_name = "apps.db"
        db_dir = mydb_utils.get_sqlite3_db_dir()
        apps_db_file = os.path.join(db_dir, apps_db_name)
        if not os.path.exists(apps_db_file):
            raise Exception(f"apps db file {apps_db_file} not found")

        conn = mydb_utils.sqlite3_connect(apps_db_file)
        b = Bork()
        #b.debug = True
        b.go(conn)
    except Exception as err:
        print("Exception ==>{}<== {}".format(err,type(err) ))
        traceback.print_exc()
    finally:
        if not conn is None:
            conn.close()
        pass
        
main()

